require_relative "../spec_helper"
require_relative "../../lib/reisbalans_hr"

describe ReisbalansHR::EmployeeIntermediateSettlements, :integration do
  let(:client) { ReisbalansHR.client }

  describe "#show" do
    let(:id) do
      ois_id = client.organization_intermediate_settlements.index.first["organization_intermediate_settlement"]["id"]
      ois = client.organization_intermediate_settlements.show(ois_id)
      employee_settlements = ois["organization_intermediate_settlement"]["employee_intermediate_settlements"]
      employee_settlements.first["id"]
    end

    subject { client.employee_intermediate_settlements.show(id) }

    it do
      is_expected.to eq(
        {"employee_intermediate_settlement"=>
          {"id"=>44,
           "effective_at"=>"2017-01-01T23:59:59+01:00",
           "committed_at"=>"2017-01-04T13:14:02+01:00",
           "employee"=>
            {"id"=>2,
             "employee_number"=>"011011",
             "full_name"=>"Daan Reiziger",
             "email"=>"daan.reiziger@workaway.nl",
             "budget_group"=>"Budgethouders",
             "cost_center"=>"",
             "department"=>""},
           "summary"=>
            {"travel_months"=>"4",
             "gross_amount"=>"0.0",
             "net_amount"=>"0.0",
             "business_rides_distance"=>0,
             "business_ov_card_distance"=>"0.0",
             "commute_rides_distance"=>0,
             "commute_ov_card_distance"=>"0.0",
             "gross_expenses"=>"0.0",
             "net_expenses"=>"0.0"},
           "specification"=>
            {"balance_after_previous_settlement"=>
              {"budget_total"=>0, "fiscal_total"=>0, "personal_total"=>0},
             "mutations"=>
              {"gross_commute"=>"0.0",
               "gross_business"=>"-167.55",
               "gross_personal"=>"0.0",
               "gross_other"=>"1068.48",
               "fiscal_tally"=>"0.0",
               "net_commute"=>"0.0",
               "net_business"=>"0.0",
               "net_personal"=>"0.0",
               "net_other"=>"0.0"},
             "balance_before_settlement"=>
              {"gross_balance"=>"900.93", "fiscal_tally"=>"0.0", "net_balance"=>"0.0"},
             "balance_after_settlement"=>
              {"gross_balance"=>"900.93", "fiscal_tally"=>"0.0", "net_balance"=>"0.0"},
             "to_settle"=>{"gross_amount"=>"0.0", "net_amount"=>"0.0"}},
           "transactions"=>
            [{"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T08:15:00+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-4.9",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>nil},
             {"cost_center"=>nil,
              "department"=>nil,
              "cost_time"=>"2015-04-01T10:49:32+02:00",
              "cost_type"=>"business",
              "from_name"=>nil,
              "to_name"=>nil,
              "distance"=>nil,
              "gross_balance"=>"-123.45",
              "fiscal_tally"=>"0.0",
              "net_balance"=>"0.0",
              "project_code"=>nil,
              "project_description"=>nil,
              "description"=>"Example subscription fee"}]}}
      )
    end
  end
end
